sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - if [ "${TRAVIS_TAG}" != "" ]; then DADDITIONAL="-t ${TRAVIS_REPO_SLUG}:${TRAVIS_TAG} "; fi
      #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ${TRAVIS_REPO_SLUG}:latest ${DADDITIONAL}.
      - docker images
      #- docker push ${TRAVIS_REPO_SLUG}
    - stage: test
      script: echo "hello"
    #  script: docker run --rm ${TRAVIS_REPO_SLUG} cat hello.txt
    #- script: docker run --rm ${TRAVIS_REPO_SLUG} cat hello.txt